name = "AbstractPermutations"
uuid = "36d08e8a-54dd-435f-8c9e-38a475050b11"
authors = ["Marek Kaluba <kalmar@mailbox.org>"]
version = "0.2.0"

[deps]
GroupsCore = "d5909c97-4eac-4ecc-a3dc-fdd0858a4120"

[compat]
julia = "1.6"
GroupsCore = "0.4"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
