name = "AbstractPermutations"
uuid = "36d08e8a-54dd-435f-8c9e-38a475050b11"
authors = ["Marek Kaluba <kalmar@mailbox.org>"]
version = "0.2.2"

[deps]
GroupsCore = "d5909c97-4eac-4ecc-a3dc-fdd0858a4120"

[compat]
GroupsCore = "0.5"
julia = "1.6"
Random = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"

[targets]
test = ["Random", "Test"]
